### ISSUE TITLE
Command Block targeting with @a (currently targets all worlds)

### ISSUE THREAD

**Issue by Faume** [Multiverse/Multiverse-Core#1009]
While using Command Blocks, the `@a` targeting variable targets all players in all worlds that meet the variable's other criteria [l=3], [lm=3], [24,64,72,5], [r=6], etc.

I have tried to find if there is a filter criteria to select the world the command should apply to or a setting somewhere in the config files, but I haven't been able to find anything. I have looked to see if there is another plugin that provides this type of functionality with Multiverse and Command Blocks, but I haven't found anything yet.

Have I missed something?

If not, would it be possible to add a "world" criteria?

For example `@a[42,64,75,3,NewWorld]` would target all players within 3 blocks of 42 64 75 in NewWorld, but no players on any other world.

Alternatively, would it be possible to add a toggle in the config somewhere to allow Command Blocks to only target players in the same world as the Command Block?

Thank you for all your hard work on this wonderful plugin!

**Comment by Kiluminator** [comment]
You can use the Range (For example: /tp @r[r=10000] @r) to select players in one world.
No matter how big the range is, it will be in the same world for sure.

But I suggest you to not increase the range over 32000. Because thats the limit Minecraft can handle at the same time.

It wont crash your server immediately, but the bigger the number is, that more time it will take until the command is executet.

If your map is not so big, that could maybe help you

**Comment by spetznack** [comment]
This is no longer a problem because it was fixed some number of versions ago. It didn't matter what radius you chose back then, it would still select players across all dimensions :)
