### ISSUE TITLE
Multiverse-Core not importing worlds properly

### ISSUE THREAD

**Issue by rexcaptain501** [Multiverse/Multiverse-Core#1524]
Hey, after importing and teleporting to worlds loaded with the latest build from Jenkins for Multiverse-Core 2.5 on Spigot 1.8 the worlds are often corrupt, have chunk errors, are the wrong world type (even sometimes as 'The End') and are completely random.

Version - I am using Spigot 1.8 version git-Spigot-"609cd55" (MC: 1.8) (Implementing API version 1.8-RO.1-SNAPSHOT)

Minecraft - I am using Minecraft 1.8.1

Plugin Version - I am using Multiverse-Core Build 692 from Jenkins (including Nether-Portals (Build 685 from Jenkins), Portals (Build 713 from Jenkins) and Sign Portals (Build 673 from Jenkins)

I also believe the Portals plugin isn't compatible with WorldEdit v6.0 and creates an error when trying to create a Portal (The work around is to delete/disable WorldEdit, make the Portal(s) (with /wand?) and reinstall the WorldEdit plugin. 

Would you please be able to update this plugin (and if possible the other Multiverse Plugins) to Spigot 1.8, it would be much appreciated :) 

Cheers,
rexcaptain501

**Comment by ajthemacboy** [comment]
Yes, we desperately need an update or at least a patch.

**Comment by TWSSYesterday** [comment]
WorldEdit 6.x branch will be supported when a commit has been made using a pull request. Multiverse Portals currently only works with the 5.x branch because it's currently more stable and we haven't updated to the new WorldEdit API.
As for the World importing errors, try updating Spigot using what I've made here: https://www.dropbox.com/s/y8cwlvxbt1bakhw/Spigot.zip?dl=0
Inside is a copy of BuildTools.jar and a shell file, when you run the shell file, it will compile a new Spigot version for you. You need the program git, which you can get here: https://github.com/msysgit/msysgit/releases/download/Git-1.9.5-preview20141217/Git-1.9.5-preview20141217.exe

**Comment by TheChampTF** [comment]
@TWSSYesterday As for buildtools, people can get that here https://hub.spigotmc.org/jenkins/

Looking forward to the updated version for WE6+

**Comment by TWSSYesterday** [comment]
@TheChampTF It's a quick way of compiling it, never said it was the only source of it.

**Comment by ryantheleach** [comment]
@TheChampTF it could be a fork of spigot for testing a pull request.

**Comment by rexcaptain501** [comment]
Just to confirm the importing problem is gone in later versions of Spigot 1.8, thanks for your help :)
