### ISSUE TITLE
Cant get my players back to the place they left

### ISSUE THREAD

**Issue by Tagmus2** [Multiverse/Multiverse-Core#1562]
So my players are automatically tp'ed to my hub world when they join, but then when they tp back into the factions world with /mvtp factions, they just arrive at the spawn of the factions world not the place they left the world. Is there an option to do this?

**Comment by TWSSYesterday** [comment]
Using /mvtp will teleport them to the spawn of the world.

**Comment by FernFerret** [comment]
Closing due to issue age (sorry). We slacked off on our issues. If you're still having this issue, please read up on [submitting a bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and post the details with a more recent server/multiverse version. Sorry again!

(You might have a look at [OpenWarp](https://github.com/PneumatiCraft/OpenWarp). Multiverse provides basic tp functions for admins, but isnt' intended to be a teleport solution)
