### ISSUE TITLE
new word rescorse pack

### ISSUE THREAD

**Issue by connor251099** [Multiverse/Multiverse-Core#1583]
hi is their a way so when i go to another word it has a needed rescorse pack

**Comment by FernFerret** [comment]
Hi there. 

This issue is either too ambiguous or does not make sense. Please read up on "[submitting a bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug)" and form a more complete bug report. We're closing this issue for now.

Please do not open a new ticket, just respond to this one and we'll reopen it.
