### ISSUE TITLE
Problem with nether? HELP!

### ISSUE THREAD

**Issue by beltez** [Multiverse/Multiverse-Core#1603]
Server and plugins version:

Spigot 1.8.3
Multiverse-core 2.5 (#697) LATEST
Multiverse-portals 2.5 (#723) LATEST
Multiverse-inventories 2.5 (#335) NOT LATEST

Problem:

No create defaults portals in nether, always is the same.
Don't need Multiverse-NetherPortals because this is my default server world "world" and "world_nether".

VIDEO: https://www.youtube.com/watch?v=e_qC9nm2ozI&feature=youtu.be

Help pls. Thanks :)

**Comment by hellphish** [comment]
I'm having the same issue. Only using multiverse Core and Portals, not Nether Portals.

**Comment by TWSSYesterday** [comment]
Check https://github.com/Multiverse/Multiverse-Core/wiki/config.yml for "portalsearchradius: 16"

**Comment by dumptruckman** [comment]
Yes, this is the default behavior of Minecraft. If there is a portal within 256 blocks of the intended location in the nether it will simply use that portal instead of making a new one. You can change this by installing Multiverse-NetherPortals and setting portalsearchradius to something small like 16. However, with portals that close together on the overworld that still may end up being the same portal.

Here's what it would be like with Multiverse-NetherPortals and a portalsearchradius of 16: Let's say the portals on the overworld are 32 blocks apart. That means the portals in the nether would be 4 blocks apart. Since 4 is less than 16 it won't make a new portal. That means the portals in the overworld would have to be at least 144 blocks apart for a new portal to be created in the nether.

The default without the extra plugin means they'd have to be a bit over 2000 blocks apart in the overworld.

**Comment by hellphish** [comment]
Sorry, I think the OP perhaps wasn't expressing the problem well. Or I am misinterpretting him/her and we have different problems. The issue I'm seeing is that portals are NEVER linked-- each trip through a portal ALWAYS creates a new one on the other side, regardless of distance.

**Comment by hellphish** [comment]
I've put together a short video demonstrating the issue. my config is in the video description https://www.youtube.com/watch?v=yK0EbBNfnIA

**Comment by FlorianFranzen** [comment]
@dumptruckman This issue clearly isn't resolved. Please reopen!

**Comment by dumptruckman** [comment]
I can guarantee you that there is nothing to resolve here. Multiverse-Core does not change the behavior of nether portals beyond blocking people from traveling to worlds they don't have permission. Multiverse-Portals doesn't use this type of portal creation behavior, so really it is ruled out as well. If this was a problem caused by the Multiverse suite, it is caused by Multiverse-NetherPortals, however, the OP was not using that plugin. Therefore, Multiverse is not the cause. **Either the server software is bugged or there is another plugin that is the culprit.**

If you are using Multiverse-NetherPortals and having an issue like this please open a ticket on it's issue tracker instead.

**Comment by FlorianFranzen** [comment]
@dumptruckman I see, you have a very good point. I apologize.

I ran into the same problem, but now that I reread what OP wrote I came to realize that in contrast to him, I was also using Multiverse-SignPortals. That makes sense as it supports using signs in conjunction with nether portals, so it is able to interferes with nether portal functionality. I will look into it some more.
