### ISSUE TITLE
Cant break blocks in some worlds

### ISSUE THREAD

**Issue by JasTheEpic** [Multiverse/Multiverse-Core#1622]
I recently started using multiverse on my server but realized that on my default world i could not break blocks. only place them. i use /mvtp to go to another world called Extra and i could break fine there so i renamed Extra world and renamed world Extra. now i can brake in my default world(old Extra) but not in Extra(old Default) ALso i tried deleting multiverse and it fixed it. but it returned to normal after reinstall

**Comment by TWSSYesterday** [comment]
Check your antibuild plugins too. Version of multiverse? Version of server?

**Comment by FernFerret** [comment]
Closing due to no response from issue owner in > 7 days. We're trying to keep the issues cleaner and the only way we can do this is by closing issues that can't be reproduced by the Multiverse Team and have no response from the owner.

If you're still having the issue described, simply comment here again (don't open a new ticket) with the requested information and we'll reopen the issue.
