### ISSUE TITLE
Gamemode switching upon teleportation

### ISSUE THREAD

**Issue by HeroThe2nd** [Multiverse/Multiverse-Core#1638]
I'm using 2.5-b699, I do not have Multiverse Inventories installed

I have two worlds on my server. One (the Hub) is in survival mode, and the other (Freebuild) is in creative mode (or supposed to be)

So in worlds.yml, I have the Hub set to survival and Freebuild set to creative. When people go back and forth between worlds it sometimes switches gamemodes, so they're in survival in the Freebuild world and vice-versa. This happens seemingly randomly. Also, when people are in the Freebuild world and they use ./tpa, ./tppos, or ./home they get switched to survival mode. 

I tried to fix this by setting every world to creative mode and using a global WorldGuard region for the Hub, flagged as survival mode. But when I go from Freebuild to the Hub, it switches to survival for a split second but then Multiverse sets it back to creative.

**Comment by TWSSYesterday** [comment]
Use /mvm set gamemode survival where it should be survival, update multiverse. Then list what happens after, ideally a log of some sort. This doesn't necessarily sound like a Multiverse issue.

**Comment by FernFerret** [comment]
Closing due to no response from issue owner in > 7 days. We're trying to keep the issues cleaner and the only way we can do this is by closing issues that can't be reproduced by the Multiverse Team and have no response from the owner.

If you're still having the issue described, simply comment here again (don't open a new ticket) with the requested information and we'll reopen the issue.
