### ISSUE TITLE
Cloning error

### ISSUE THREAD

**Issue by Eonichope** [Multiverse/Multiverse-Core#1656]
Server: CraftBukkit version git-Spigot-13716d9-0899683 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
Plugin Version: Multiverse-Core v2.5-b699
Problem: When I attempt to clone my world, this happens:
![2016-02-15](https://cloud.githubusercontent.com/assets/7019009/13062990/3b272060-d3f8-11e5-9020-bb77d46855d8.png)
![2016-02-15 1](https://cloud.githubusercontent.com/assets/7019009/13062995/47e01334-d3f8-11e5-97ae-2c2c92aa78c1.png)

**Comment by FernFerret** [comment]
Hi there. We're cleaning out the issue tracker since we (mostly me) have mistreated it.

This issue does not have enough information to warrant keeping it open, so I'm going to close it. If you're no longer interested in getting it solved or you already found a solution, great! 

If you're still experiencing a problem, please have a look at [Reporting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug) and reopen this ticket! Thanks!

You should also make sure you're running the [latest spigot code](https://www.spigotmc.org/wiki/spigot-installation/) as well as the latest [Multiverse-Core](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/) and [Multiverse Plugins](http://ci.onarandombox.com/view/Multiverse/).
