### ISSUE TITLE
World could NOT be deleted!

### ISSUE THREAD

**Issue by TheOtakuJames** [Multiverse/Multiverse-Core#1663]
Hi there, 
I am running Spigot 1.9, and Multiverse-Core 2.5-b699.

I am trying to delete my Survival, Survival Nether, and Survival End worlds (world, world_nether, world_the_end) but when I type /mvconfirm it comes up with the message "World could NOT be deleted!"
In console, this message then appears: "WARN World 'world' could not be unloaded. Is it a default world?" My default world is "hub", so none of the 3 survival worlds should have that message, especially the Nether and End ones.
How can this be fixed, as I am trying to get a new Survival (and all other types) world. 
Thanks in advance.

**Comment by FernFerret** [comment]
First, sure you've updated Multiverse-Core to the [latest build](http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Core/). At this time it's **716**.

If that still doesn't help, please post some logs and read [Submitting a Bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug).

**Comment by dumptruckman** [comment]
The sad fact of the matter is, `/mv delete` tries its very best to delete a world but will often fail because something else (another plugin probably) has a hold of the world reference and will not let go of the file handle. There is absolutely nothing we can do in Java to get around this problem.

@FernFerret we probably should have the message say "sorry, we tried to delete the world but it failed. sometimes this happens. you will need to shut down your server and delete the world manually."

**Comment by FernFerret** [comment]
@dumptruckman agreed. do you have a plugin that can do this for us for testing? (hold a world reference?)

**Comment by leasoncre** [comment]
use "/mv remove [world]"
stop server if necessary, and delete the [world] files
:)
