### ISSUE TITLE
Multiverse error

### ISSUE THREAD

**Issue by BlackRavenMC** [Multiverse/Multiverse-Core#1677]
I get error when i teleport to someone or something like that.

http://pastebin.com/swcEpVJQ

**Comment by TWSSYesterday** [comment]
Versions of everything? Entire log file?

**Comment by BlackRavenMC** [comment]
Active Plugins (42): CleanroomGenerator: 1.0.0, CoreProtect: 2.12.0, dynmap: 2.3-SNAPSHOT-1132,  
WorldEdit: 6.1.1-SNAPSHOT;3459-94ae1be, HealthBar: 1.8.3, SkinsModule: 11.0,  
Essentials: TeamCity, PlugMan: 2.0.8, Spawner: 2.5-0622a49, Votifier: 1.9,  
BanManager: 5.9.0-SNAPSHOT, WorldGuard: 6.1.2-SNAPSHOT;1652-c9b8e9f, ProtocolLib: 3.7.0-BETA,  
EssentialsChat: TeamCity, DeathMessages: 3.1.1, PermissionsEx: 1.23.4, StaffChat: 1.3.1,  
GAListener: 1.3.2, Vault: 1.5.6-b49, SalvageSmelter: 0.1.8, EssentialsSpawn: TeamCity,  
Jobs: 2.63.2, ScoreboardStats: 0.9.8, Trading: 3.2, PlotSquared: 3.3.1, LWC: 4.5.0-SNAPSHOT,  
Thirst: 2.1, Multiverse-Core: 2.5-b717, Citizens: 2.0.17-SNAPSHOT (build 1325),  
VanishNoPacket: 3.20, Multiverse-Inventories: 2.5-b406, PlayerVaults: 3.5.8-SNAPSHOT-b193,  
Multiverse-Portals: 2.5-b740, BungeeTabListPlus: 2.4.1, ServerShop-GUI: 1.6.4,  
Denizen: 0.9.8-SNAPSHOT (build 1611), ChestShop: 4.0-r2, AuthMe: 5.2-SNAPSHOT-b881,  
HolographicDisplays: 2.1.12, Webizen: 0.2.0, Depenizen: 0.2.2 (build 309),  
Multiverse-NetherPortals: 2.5-b708

**Comment by TWSSYesterday** [comment]
Whole log file?

**Comment by BlackRavenMC** [comment]
Yea.. but there is already that bug report posted 2 days ago and no one have answered, and I can't really give whole log file because there is other people IP's and chat..

**Comment by FernFerret** [comment]
This is not a Multiverse-Core issue. It's with Multiverse-Inventories. I'd recommend giving [PWI](https://www.spigotmc.org/resources/per-world-inventory.4482/) a look as we're not supporting Multiverse-Inventories at this time due to time constraints of the developers.

PWI supports importing your Multiverse-Inventories settings.

I would only suggest using another plugin if it was open source, and [PWI is](https://bitbucket.org/Gnat008/perworldinventory/overview).
