### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by pookshuman** [Multiverse/Multiverse-Core#1679]
Hello,

I keep getting errors like this http://pastebin.com/meTc2U0i in the console.

I don't know what it means.

**Comment by pookshuman** [comment]
I forgot, here is the version info http://pastebin.com/zKdARtcu

**Comment by FernFerret** [comment]
This is not a Multiverse-Core issue. It's with Multiverse-Inventories. I'd recommend giving [PWI](https://www.spigotmc.org/resources/per-world-inventory.4482/) a look as we're not supporting Multiverse-Inventories at this time due to time constraints of the developers.

PWI supports importing your Multiverse-Inventories settings.

I would only suggest using another plugin if it was open source, and [PWI is](https://bitbucket.org/Gnat008/perworldinventory/overview).
