### ISSUE TITLE
Inventory Items causing errors...

### ISSUE THREAD

**Issue by austindkelly** [Multiverse/Multiverse-Core#1680]
This is just a quick sample of an error that occurs with some particular metadata attached to items on our server. This maybe unique, but I am looking for a solution. Players seem to have inventories intact, except in some cases where they cross worlds, and permissions are not the same. 

http://hastebin.com/woyomuzaka.avrasm

Noting this particular line:

> [02:48:30 WARN]: [Multiverse-Inventories] Could not parse item: ItemStack{LEATHER_BOOTS x 1, LEATHER_ARMOR_META:{meta-type=LEATHER_ARMOR, display-name=DELTA Boots, lore=[Offical Armor of DELTA], enchants={PROTECTION_ENVIRONMENTAL=4, PROTECTION_FIRE=4, DURABILITY=3, PROTECTION_FALL=4, PROTECTION_EXPLOSIONS=4, PROTECTION_PROJECTILE=4, THORNS=3}, color=Color:[rgb0x282850]}}

**Comment by FernFerret** [comment]
This is not a Multiverse-Core issue. It's with Multiverse-Inventories. I'd recommend giving [PWI](https://www.spigotmc.org/resources/per-world-inventory.4482/) a look as we're not supporting Multiverse-Inventories at this time due to time constraints of the developers and it has several known issues.

PWI supports importing your Multiverse-Inventories settings.

I would only suggest using another plugin if it was open source, and [PWI is](https://bitbucket.org/Gnat008/perworldinventory/overview).
