### ISSUE TITLE
Spigot/PaperSpigot 1.8.8 error!

### ISSUE THREAD

**Issue by xGioChR** [Multiverse/Multiverse-Core#1683]
Hello.
Yesterday I tried to generate a world called "Free" with the world generator "RealisticWorldGenerator".
It gives me this error.
http://pastebin.com/Ly3efAFE
Am I doing something wrong? Thank you anyway.

**Comment by FernFerret** [comment]
This exception is not caused by multiverse, but rather your world generator:

It seems that this plugin may not know about `MUTATED_MESA_CLEAR_ROCK` which is present in your spigot version.

I'm still not positive which one is out of date or too new (either your generator plugin or server) but I'd look there first.

Here's the line of the traceback you posted that tells us it's not multiverse, but the generator plugin:

```
Caused by: java.lang.NoSuchFieldError: MUTATED_MESA_CLEAR_ROCK
        at de.yellowphoenix18.realistic.populators.GrassPopulator.populate(Unknown Source) ~[?:?]
```

**Comment by main--** [comment]
FYI: I made the [unsafe call wrapper](https://github.com/Multiverse/Multiverse-Core/blob/d2d243caeccaba2cd560527564bfafbe4abba868/src/main/java/com/onarandombox/MultiverseCore/utils/WorldManager.java#L439) to catch errors like this one and direct people away from our bug tracker when it's not our fault. I didn't apply it to `creator.createWorld()` because we already have a [check](https://github.com/Multiverse/Multiverse-Core/blob/master/src/main/java/com/onarandombox/MultiverseCore/utils/WorldManager.java#L467) there which however catches only `Exception` and not `Throwable` and therefore not this `NoSuchFieldError`.

**Comment by FernFerret** [comment]
Ah! Good **catch**, I'll fix this soon.

#javapuns

**Comment by dumptruckman** [comment]
Heh, I actually already put in further exception catching for similar problems but i didn't do Throwable, like @main-- said.

**Comment by dumptruckman** [comment]
Er.. I just added a null check to createWorld.
