### ISSUE TITLE
Forge mods not loading  Multiverse core 1.6.5 1.7.10

### ISSUE THREAD

**Issue by REVIEWGAMINGMAN** [Multiverse/Multiverse-Core#1693]
I have been trying to build a spawn on a mcpc cauldron or kcauldron

**Comment by FernFerret** [comment]
I'm not sure what this issue is or means. I think we've decided we'll support 1.8 and 1.9 (the last 2 stable versions) but nothing older. Is this issue related to 1.8 or 1.9?

**Comment by FernFerret** [comment]
Closing due to no response from issue owner in > 7 days. We're trying to keep the issues cleaner and the only way we can do this is by closing issues that can't be reproduced by the Multiverse Team and have no response from the owner.

If you're still having the issue described, simply comment here again (don't open a new ticket) with the requested information and we'll reopen the issue.
