### ISSUE TITLE
Multiverse worlds not disappearing

### ISSUE THREAD

**Issue by GunnerFRC** [Multiverse/Multiverse-Core#1699]
Hello,
I'm currently using PlotMe to try to make worlds. I have installed everything correctly, and added the extra line of code to bukkit.yml for PlotMe. When I tried to make a new world with the generator, it says World creation FAILED. It won't let me delete the world, saying could NOT delete the world, and it still appears in /mv list as an unloaded world after deleting the folder completely in my FTB client. I want to recreate the world, but I can't because I can't use the same name. Restarting the server after deleting the folder from FTB and config does not remove it. How can I fix this!

**Comment by FernFerret** [comment]
Have you tried {{/mv remove NAME}}. It's featured in the [command reference](https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#remove-command).

**Comment by FernFerret** [comment]
Closing due to no response from issue owner in > 7 days. We're trying to keep the issues cleaner and the only way we can do this is by closing issues that can't be reproduced by the Multiverse Team and have no response from the owner.

If you're still having the issue described, simply comment here again (don't open a new ticket) with the requested information and we'll reopen the issue.
