### ISSUE TITLE
When I do /time set 0 it sets all the worlds in the server to that time, not just the one I'm in, why? and how can I stop this?

### ISSUE THREAD

**Issue by Xinoms** [Multiverse/Multiverse-Core#1704]
Whenever I set the time in the main world of my server it changes the time in the other world I have on the server, is there nay news on whether theres a solution to this???

**Comment by Xinoms** [comment]
Can you help @FernFerret  ???

**Comment by FernFerret** [comment]
So, `/time set X` is a built-in command. It *should* only affect the current world. I'll have to look at it, but it won't be multiverse, it'll probably be a bug in the Multiworld API that Spigot or something else implenets.

Can you please post the results of `/mvv -g`?

**Comment by FernFerret** [comment]
Closing due to no response from issue owner in > 7 days. We're trying to keep the issues cleaner and the only way we can do this is by closing issues that can't be reproduced by the Multiverse Team and have no response from the owner.

If you're still having the issue described, simply comment here again (don't open a new ticket) with the requested information and we'll reopen the issue.

**Comment by bud-lwos** [comment]
Just wanted to bump this.  I'm having the same issue. 

I issued /mvv -g.  The results are here: https://gist.github.com/anonymous/38e4991bbc45cdce783f797651f45982

Thanks
