### ISSUE TITLE
Create worlds like this if world already exists: username1, username2, username3, etc... 

### ISSUE THREAD

**Issue by vliegendevogel** [Multiverse/Multiverse-Core#1705]
Dear guys, 

in the file https://github.com/Multiverse/Multiverse-Core/blob/master/src/main/java/com/onarandombox/MultiverseCore/commands/CreateCommand.java there is an issue. I want to execute the following command using ChestCommandsGui plugin: 

`mv create {player} normal -g VoidWorld `

But if I executed it twice, it cannot be run, because the world named for example "username" already exists, thanks to this code: 

`if (worldFile.exists()) {
            sender.sendMessage(ChatColor.RED + "A Folder/World already exists with this name!");
            sender.sendMessage(ChatColor.RED + "If you are confident it is a world you can import with /mvimport");
            return;
        }`

I suggest to change it to something like this: 

if the worldFile exists, and the worldName equals the username of the player, the worldName becomes username+1 

with an outcome like username2. So in the folder list, I would like to see two worlds: username1, username2. And if I run the command again, a new world like username3 will be added, and so on.

**Comment by FernFerret** [comment]
Why not do the increment before sending the command it to Multiverse? You
could also use a date or any other counter (uuid?)

In addition, it would have to be a for loop, because if it counted up every
time, then you'd run into much of the same problem if it was just the if
with a one up counter.

Think of how the `touch` command (or `cp` or `mv`) works on linux. If every
time I ran `touch`, I got a different filename, It'd drive me batty.

I personally don't like this change suggestion at all and don't think we'll
be implementing it (but obviously, this is why we keep MV open source,
you're free to fork it and make the change yourself!). You could also write
a very small plugin that would call the MV API to do this as well.

**Comment by vliegendevogel** [comment]
I am sorry but I am actually not a programmer. I can only try to understand existing pieces of code but writing them myself has proven too hard on me. Maybe you thought I could write it myself. That is why I am asking you guys. For example, I need String worldName to be equal to the username of the currently logged in player. I don't know what to choose from the dozens of possible packages on https://jd.bukkit.org/. Do you know anyone knowledgable about Multiverse who can help me?

**Comment by FernFerret** [comment]
What I'm saying, is that this feature simply isn't generic enough or is deemed to difficult to make generic inside Multiverse. Our team has a lot on their plate and little spare time to accomplish it, so I'm going to close this issue.

With regard to asking us, that's fine and all but what I'm effectively telling you is our team does not have the resources to dedicate to this feature. I'm passionate about Multiverse. I want to keep it alive and specific features, while they may be perfect for your server, might not fit in the vision for a generic world manager such as Multiverse. This is one of those features.
