### ISSUE TITLE
bad permission

### ISSUE THREAD

**Issue by tryolivier** [Multiverse/Multiverse-Core#1711]
Hi :)

 I use multiverse signs to TP between 2 world http://dev.bukkit.org/bukkit-plugins/multiverse-signportals/
 It works for pour /op persons but not for others 
 What is the permission ??
 I search but I only find to create or validate :https://github.com/Multiverse/Multiverse-SignPortals/wiki/Big-list-o-permissions

 Thanks a lot for your help !

**Comment by FernFerret** [comment]
This issue either does not have enough details, or details have been requested and not provided. Please read up on "[submitting a bug](https://github.com/Multiverse/Multiverse-Core/wiki/Submitting-a-Bug)" and form a more complete bug report.

Please make sure to include steps to reproduce your problem, since I don't fully understand the question.
