### ISSUE TITLE
An bug founded.

### ISSUE THREAD

**Issue by DutchUser** [Multiverse/Multiverse-Core#1786]
Hello.

Short time ago i used the enforce permission of MV.

But after that the portals dont work anymore while it is set to "false" in the Multiverse-Portals config.

And when i set it to "false" to in the MV-Core the portals work again.

Multiverse-Core Version: 2.5-b717
Multiverse-Portals Version: 2.5-b725
Server Version: 1.11.2-R0.1-SNAPSHOT

Multiverse config's
Core: http://pastebin.com/RcpK7TLP
Portals: http://pastebin.com/fmgqhSjc

Main Issue:
When the enforceaccess is set to "true" portals dont work anymore. While they can warp to that world. And players with OP can use portals.

**Comment by Jadiction** [comment]
You need to give proper permissions. I tested enforcements for both portals and worlds and they worked fine as long as the proper permissions were given.

World: multiverse.access.<WORLD>
Portal: multiverse.portal.access.<PORTAL NAME>

Closing ticket because it's 2 years old and the issue wasn't able to be replicated. If you still use Multiverse at this time (and use the updated version) and continue to have issues, please open a new ticket.
