### ISSUE TITLE
Empty world isn't correct

### ISSUE THREAD

**Issue by Thisie** [Multiverse/Multiverse-Core#1803]
If I import an Empty world from anywhere, Multiverse don't make an Empty world. He just Import a little bit of the map (only where built) please fix it I hate it when I import an Empty world and I see that he remove a little bit from a normal world. :( AND!!! make a subcommand for create an Empty world. eg. /mv create Test -t Empty

Thanks in advance,

Thijs

**Comment by MrRiptide** [comment]
This is not a bug, instead it is because since those chunks have not been loaded before, they won't be empty when you try to load new chunks.  A way to make empty worlds is to use a generator like CleanRoomGenerator or EmptyWorldGenerator to generate an empty world.  Just add the plugin, and then run /mv create <Name of World> normal -g <Name of Generator>
