### ISSUE TITLE
World load order

### ISSUE THREAD

**Issue by Greenfoot5** [Multiverse/Multiverse-Core#1805]
I am trying to load in a world using worldboarder (/we fill) but run out of memory. This is fixable if I can reload it. However, the world I am trying to load in loads after worldboarder therefore worldborder thinks the world doesn't exist and cancels the command. Some worlds load before worldborder loads. Is there a way to change the order in which worlds load?

**Comment by MrRiptide** [comment]
I'm having a problem with world loading order as well.  It causes problems with plugins not thinking that a world is there when it actually is.

**Comment by Greenfoot5** [comment]
I believe servers load files in alphabetical order

**Comment by MrRiptide** [comment]
Spigot actually loads the plugins intitally based on when the plugin tells it to, based on the plugin.yml file within the jar, but after that level I don't know what it is based on.  In multiverse, it seems to be loading my worlds in this order:
world
world_the_end
Hub
But in my worlds.yml file it goes in this order:
world
world_nether
world_the_end
Hub
It doesn't seem to be putting anything into the logs about a nether world...
I also tried reorganizing the world.yml file and it is exactly the same.  No plugins seem to know about world_nether, and even though it shows it in the /mv list, multiverse seems to not know how to take me there...

**Comment by Greenfoot5** [comment]
Idk then.

**Comment by dumptruckman** [comment]
I'm afraid I don't understand the original issue. Wouldn't you want all worlds to load before worldborder?

The order the worlds load in is not something you can configure. Bukkit does not gaurantee any kind of order when loading from a configuration file. That means that changing the order of the worlds in world.yml doesn't do anything because that's just not how Bukkit works.

In any case, the order Multiverse loads worlds shouldn't matter at all. Bukkit loads the default world (and it's nether and end) before most plugins (including Multiverse) are loaded. Then when Multiverse is loaded it loads in all the other worlds in worlds.yml. No other plugins will be loaded _while_ Multiverse is loading worlds.

**Comment by MrRiptide** [comment]
I think what is happening for Greenfoot5 is that some of the worlds load, and then in between world b and world c loading, the worldborder plugin loads.

**Comment by dumptruckman** [comment]
@MrRiptide The only way that is happening is that the default worlds loaded, WorldBorder loaded, then all the worlds created/managed with Multiverse load. Worldborder _cannot_ load during the Multiverse worlds.

If you want WorldBorder to load after Multiverse, you can edit the plugin.yml within the jar file and put the edited version back into the jar file. You would need to add `depend: [Multiverse-Core]`.

**Comment by Greenfoot5** [comment]
I thought that changing the world load order would allow for me to have a world load perform a certain plugin. I thought this was possible because my default world had loaded and then worldborder and then my multiverse world. I didn't know there was a difference.
