### ISSUE TITLE
Cannot Import Worlds in FTB Infinity Evolved

### ISSUE THREAD

**Issue by Tonacane** [Multiverse/Multiverse-Core#1809]
**When trying to import a Spawn world:**
![](https://i.gyazo.com/b6da91266af03d022e28dc1557b715c8.png)

**I get an error:**
![](https://i.gyazo.com/1b09dc4ed908fb470c230e8f5f99de8a.png)

**My folder looks like this:**
![](https://i.gyazo.com/ec71478998f068d553deecd43cb3c268.png)

**I'm playing FTB Infinity Evolved 1.7.10.**

I'm not sure if its because it needs to be an FTB world or not. Help please :D

**Comment by MrRiptide** [comment]
Have you tried importing in spawn in full lowercase?  Some aspects of the plugin are case sensitive.

**Comment by Jadiction** [comment]
As MrRiptide suggested, try using all lowercase for the world name, since your folder (world name) is all lowercase. Currently, it's best practice to have all world names to be lowercase as well. Closing this ticket; if this indeed an issue on the latest Multiverse version, please open another ticket.
