### ISSUE TITLE
Multiverse respawn point not working /mv setspawn not working

### ISSUE THREAD

**Issue by TrionicAang** [Multiverse/Multiverse-Core#1833]
Am So Hi Everyone :D i guess lol. So i Need Help With Multiverse, When I Type In /mv setspawn Then Is Says Spawn Set And The Cords And Then When I Die In That World I Respawn There But When i Die In Like Another One I Respawn Somewhere Else I Have Essentials But Not Essentials Spawn

**Comment by Relaking** [comment]
That's probably because the /mv setspawn only sets the spawn for the current world. 
To achieve what you want you have to set the respawnworld to the world you'd like your players to respawn in. You can do that with **/mv modify set respawnWorld _worldname_** (instead of worldname the name of the world you want your players to respawn in)

**Comment by Jadiction** [comment]
Closing ticket because the solution is posted (by auroasmiles).
