### ISSUE TITLE
Gamerules Not working

### ISSUE THREAD

**Issue by FatmanC** [Multiverse/Multiverse-Core#1864]
Hi
I have a problem where i set gamerule keepinventory true which doesnt work. I keep getting failure messages. i have done it with naming a world, and without and neither are working for me.

At the moment, keep inventory is only working in normal worlds, but not for the end or nether

i have also tried using the console to set it, with the same issue as in game - "failure: gamerule keepinventory cannot be set to true'

please help
thanks

**Comment by FatmanC** [comment]
fixed it. Sorry for othering anyone

**Comment by ryantheleach** [comment]
@FatmanC Your issue is caused because of Sponges multiworld support. In order to support differing game rules across worlds, Sponge splits the gamerules by worlds.

In order to set a gamerule that applies to a world, you need to be in the world that you use the vanilla gamerule command on.

As for the error that it can not be set to true, that is surprising. What was the fix that you came across?

**Comment by FatmanC** [comment]
the fix was i grew a braincell or two. It was a case sensitive issue. i was doing keepinventory, when you wiki clearly says keepInventory once i did that.... i was fine.
