### ISSUE TITLE
Option so Changing Worlds Doesn't TP Them Back to Spawn

### ISSUE THREAD

**Issue by Techno3600** [Multiverse/Multiverse-Core#1882]
Hey,

I don't like how when my players teleport to different worlds, they are always teleported back to spawn, if there a way I am able to make it so they are able to automatically spawn back to their last location?

Thanks
Techno

**Comment by Qrylor** [comment]
I have to laugh at seeing this.  It is the exact same request I made 5 years ago and just read my request before looking at current issues. I don't know if they plan on changing their verdict but at the time they had no intentions of it (drawing line at storing player data).  Personally would still love the option in-part because the additional add-on I was using hasn't been updated since 2013 (maybe there is another replacement).

**Comment by benwoo1110** [comment]
Mulitverse inventories have a last location feature. https://github.com/Multiverse/Multiverse-Core/wiki/Shares-List-(Inventories)#optional-shares---must-be-enabled-via-mvinv-toggle-sharename-or-they-have-no-effect
