### ISSUE TITLE
Loaded and imported worlds are being overwritten and reset.

### ISSUE THREAD

**Issue by AlucardBFahrenheit** [Multiverse/Multiverse-Core#1902]
**I am running a small modded minecraft 1.7.10 server using KCauldron 1.7.10-1614.201 wich is the latest version of KCauldron and I am running the latest version of Multiverse-Core on the server.**

The problem that I am having is, that every time I import a new world or restart the server the specific world and all the other worlds are being reset and overwritten (worlds that are flat are completely flat with all buildings gone) and all normal worlds being completely new generated from the ground up, with all buildings being gone as well. Plot worlds have all plots empty and became unowned.

**Currently used plugins are :** 
AuthMe-5.2-legacy, AutoMessage, Clearlag, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, GriefPrevention, Multiverse-Core-2.5, NoteBlockAPI-1.1.0, PlotSquared, PluginConstructorAPI, ProtocolLib, ScoreboardAPI, SignWarper, Simple-Prefix, SuperCensor_v3.3, UltimateHeadFinderv1.4.0, WarpSigns, WorldBorder, icJukeBox, worldedit-bukkit-6.1, worldguard-6.1

Here the server logs if they are useful:
https://gist.github.com/AlucardBFahrenheit/79d10f3c610e7b9edcf22294cadd0d86

Notable is that this issue did not happen on the 1.10.2 server I had.

**Comment by Jadiction** [comment]
Hi, this is an old post, but are you still running a server with this issue? If so can you try using the latest (dev) version of Multiverse-Core and try again? I also don't see any indication that this is a Multiverse error in your stack traces.
I only see error pretty commonly:

`[22:44:04] [Server thread/WARN]: [Multiverse-Core] WorldManager: Can't load this world because the folder was deleted/moved: <WOLRDNAME>
[22:44:04] [Server thread/WARN]: [Multiverse-Core] Use '/mv remove' to remove it from the config!`

Are your world directories being moved or deleted upon startup or something or are these not the worlds you're referring to?

**Comment by Jadiction** [comment]
Closing old ticket. Make sure to update to the latest versions of Multiverse (Core, Portals and any others you may use). Please open a new ticket if you believe you are encountering a bug. You can receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
