### ISSUE TITLE
Huge problem?

### ISSUE THREAD

**Issue by RainOfPain125** [Multiverse/Multiverse-Core#1905]
I have no idea anymore..

After spending months in a custom flatworld we named world_test I came online yesterday, did /mvtp world_test and it said "Multiverse doesn't know how to take you to world_test"

So I tried to load it with /mv load world_test and it told me to import it

So I did /mv import world_Test normal and now the entire world is just flat. Nothing we built is there anymore. I freaked out and tried to use data recovery but the files had been overwritten it seems. Why? I don't get what went wrong..

I did some testing on a separate server with the data files of a backup I made a LONG time ago and that doesn't work either. This is what I got out of testing with my separate server -

https://image.ibb.co/iSbywx/fixurshit.png

Very contradicting. Saying it  doesn't know about the world then saying in-game chat "world test already knows about world_test" after typing /mv import world_test normal.

**Comment by Jadiction** [comment]
This issue seems situational, A plugin could've broken your world, server / PC corruption, etc. I'll leave it open for a developer to look at in case there is an issue with MV. I would, however, not recommend naming your images "fixurshit". The Multiverse plugins aren't paid for, they purely work on these plugins for the community. They are in no way obligated to do what they do.
