### ISSUE TITLE
Cloning world - indirect issues

### ISSUE THREAD

**Issue by jaylawl** [Multiverse/Multiverse-Core#1922]
Yesterday i cloned a world for the first time. I was surprised to see that all the entites of the original world got copied along with the world. I didn't need them in the copy of the world, so i ran around getting rid of them using the /kill command.

I was then surprised to return to the original world and see, that all the entities i killed, got killed in the original world too.

This is due to the entities being copied exactly, even with the same UUID - where entities with the same UUID generally aren't a good thing.

I'd like to suggest an option not to copy entities when cloning worlds or atleast add a warning message about this matter.

Otherwise, on a side not, been a long time user of Multiverse. Top notch solid plugin, thanks! And thanks for reading this.

**Comment by altrisi** [comment]
Are you sure it isn't because /kill kill entities in ALL worlds when using it in a server?
At least, that's what have always happened to me, but maybe it's different.
If you are using `/kill @e`, try specifing a radius with `[r=radius]`. So, for example, you could do `/kill @e[r=99999]` (I think there was a maximum range, but I can't remember what is it).

_I'm talking about vanilla_ `/kill` _command. If you are using it from another plugin, I can't say anything without more information. Also, my current experience with that command in a plugin server is only 1.8.8._

**Comment by jaylawl** [comment]
Thanks for your response. You're correct, but i was and am aware of how minecraft's kill command works. I was using a low radius to make sure i only kill specified entities in the desired radius. I actually have a script in place that prevents me from using the /kill command without specifying [r=]
