### ISSUE TITLE
respawn game-mode after death

### ISSUE THREAD

**Issue by RedstoneFuture** [Multiverse/Multiverse-Core#1925]
If I defined in the worlds.yml:

```
worlds:
  test1:
  [...]
    respawnWorld: 'test1'
  [...]
    gameMode: CREATIVE
  [...]

```

and I death, I respawn with the survival game-mode.

If I teleport me to the world 'test1' at normal, I get creative modus. Thus the game-mode configuration is correctly.

Do Multiverse check the in Multiverse configurated game-mode at the respawn? Or can you add this, please?

A: **a respawn-gamemode option**

or

B: **give the user after a respawn the same in the world.yml defined gamemode**

**Comment by Jadiction** [comment]
Hi, I was unable to replicate this.
I followed the steps you gave above:
>In a creative gamemode world with respawnWorld set to a survival world
>Died in creative gamemode world
>Respawned in survival gamemode world with my gamemode changed to the respected gamemode in Multiverse configuration.

I'd recommend checking out your other plugins for conflictions. Because this is a year+ old issue post, I will close the ticket. If you are still having issues while using the latest Multiverse version, please feel free to open a ticket!
