### ISSUE TITLE
Datapack per-world configuration

### ISSUE THREAD

**Issue by EthanJR** [Multiverse/Multiverse-Core#1949]
I've found datapacks will only be recognised when placed in the main world folder directory. Putting them in the directory of any non-main world will result in them not being read. However, a working datapack when enabled will still apply to all worlds.

Is there currently a work-around or support for getting datapacks to only be configured for certain worlds?

**Comment by ryantheleach** [comment]
This occurs due to a disconnect between the bukkit idea of worlds, and the minecraft view of worlds.

In the minecraft model, a world is a 'save file'. You select them from a single player screen (if playing single player) and every world has multiple dimensions.

In the bukkit model, what they call a world, gets mapped to a Minecraft dimension.

So datapacks are effectively, per server level, not per Minecraft dimension.

Multiverse does not make changes directly to Minecraft. It has to use the Bukkit/Spigot API.

To my knowledge, Neither Bukkit/Spigot API's contain the necessary features to make data packs, per dimension (and thus, per world)

(Opinion following) I think Minecraft is due for a reckoning. Either the Multi-world support in server side API's need to start seriously thinking about modding the underlying structure to allow **real** multiple worlds loaded on a server. 

Or they need to start recommending users use multiple real servers, and bridging the gap using proxy software such as Bungeecord.

The first is more technically difficult, and prone to errors that will affect everyone. Where as the latter moves the complexity to plugins and the community, which can be incredibly frustrating to configure.

**Comment by FunkyToc** [comment]
Hey,

I have a pretty the same issue, or juste a different vision of this problem. So i prefer expose it here than creating a new topic.

**My point is :** map makers can place their datapacks in the main world. That's fine. But, how to target a single world ?
In MC vanilla, we can use a Dimension selection. "Dimension" means "type of world". So we can't really target a single world between multiple overworlds.
`/execute in minecraft:overworld run [...]` will works for all our overworlds.

It's a bit annoying (for mapmakers). Of course, we have alternatives solution, like use differents tags ("world-A", "World-B"...) on each worlds, aplied with a local command block, but this is definitely not a good way to do it. May your plugin change anything about it ?


Thanks, and congratulations for your work !
