### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by kuba3234** [Multiverse/Multiverse-Core#1984]
when i change the
prefixchat: 'true' to
prefixchat: 'false'
and save file, turn server on the config file still
prefixchat: 'true'
it's 13.2 version

**Comment by kuba3234** [comment]
ok now on chat everything is white there is no [world]<nick>:hi
there is <nick>:hi i want how it is in normal vanilla mc
i used team command and my team is blue and i want every nick on blue on chat

**Comment by Jadiction** [comment]
Since prefixchat is working properly, the rest of the issue appears to be misconfiguration with your chat settings. I'd suggest finding a plugin that manages it. For example, EssentialsX & a permissions plugin does the job fine when adding prefix and suffixes to names. Due to this not being Multiverse related, I am going to close the ticket. If you have problems with Multiverse while on the latest version in the future, please contact support on Discord or open a new ticket on here.
