### ISSUE TITLE
Could not pass event PlayerTeleportEvent (1.14)

### ISSUE THREAD

**Issue by PenguinOwl** [Multiverse/Multiverse-Core#2015]
```10.06 20:41:22 [Server] ERROR Could not pass event PlayerPortalEvent to Multiverse-Core v3.0.0-SNAPSHOT-b760
10.06 20:41:22 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerPortalEvent.getPortalTravelAgent()Lorg/bukkit/TravelAgent;
10.06 20:41:22 [Server] INFO at com.onarandombox.MultiverseCore.listeners.MVPlayerListener.playerPortal(MVPlayerListener.java:307) ~[?:?]
10.06 20:41:22 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor53.execute(Unknown Source) ~[?:?]
...```

On latest build as of 6-10-19, error seems to occur whenever a play goes through a nether portal. Server is Paper, build 72.

**Comment by Jadiction** [comment]
Currently, TravelAgent was removed and is causing some issues in Multiverse. This will be fixed soon, however.

A message from Dumptruckman:

I just want to let you know that I understand there are some issues with Multiverse running on 1.14. The reason behind this is the removal of something called the TravelAgent. Because this was removed, some stuff broke related to nether and end portals. In particular, Multiverse-NetherPortals is not working at all.

You should all know that 1.14, 1.14.1, and 1.14.2 have been full of problems in general. What you may not know is that TravelAgent is going to come back. When it does, most of the things that 1.14 broke in MV will no longer be broken. Since I have so little time to devote to this project, it seems to be in my best interest to just wait for that to happen rather than make a bunch of changes I will need to change back later. I know you're all anxious to get your servers working perfectly for 1.14 but from what I hear, 1.14 is just far from perfect itself right now. Please be patient while we wait for better days.
