### ISSUE TITLE
End World Turn Backs In to Normal World after restart

### ISSUE THREAD

**Issue by SakizciAdam** [Multiverse/Multiverse-Core#2111]
When I create end world for my survival(I am using` /mv create survivalend end`)
I can create world and players can tp but when I restart the server it turns back into normal world.

**Comment by Pet0203** [comment]
Got this issue too.

**Comment by Jadiction** [comment]
I've been using the latest paper with Multiverse for a while now and have never experienced this nor heard of it. If you can find a way to reproduce this, please open a ticket with how to do so. Otherwise, it sounds like it's likely another plugin or something else of the sort. You can receive support on the [Multiverse Discord](https://discord.gg/NZtfKky) if necessary.
