### ISSUE TITLE
Unable to import worlds with spaces

### ISSUE THREAD

**Issue by nicegamer7** [Multiverse/Multiverse-Core#2201]
I haven't confirmed this myself.

If I can reproduce this issue, I'll see if I can fix it and open a pull request.

**Comment by Jadiction** [comment]
Worlds shouldn't have spaces anyway. The standard is lowercase with no spaces. It's recommended to use aliases for a nicely formatted world name.

**Comment by nicegamer7** [comment]
I agree. However, in the documentation it lists an example of importing a world with spaces.

Either we remove the example and add a note on aliases, or we fix it. I'm willing to do either, just let me know.

**Comment by Jadiction** [comment]
Not up to me, but I'd honestly just say both. We remove the example as it shows poor naming conventions and also fix the importing issue with world spaces because there will always be people who don't know the standards or simply just ignore them.
By the way, when importing a world with spaces, don't you use quotes? I.E `/mv import "World two" normal`? I haven't tried this myself because I've never used a world with spaces.

**Comment by nicegamer7** [comment]
I've also never tried it, this report came from the Discord support server. I just thought I'd add it here and fix it if needed.

**Comment by Icebluewolf** [comment]
This is confirmed, I had the same world one I did.    mv import "my world with spaces" NORMAL.
changed the name of the file to "myworld".    and did    mv import myworld NORMAL and it worked.

**Comment by benwoo1110** [comment]
Reproducible bug which produces `net.minecraft.server.v1_15_R1.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:test 2` error.

Mostly like a Minecraft issue which disallows spaces to be in worldnames.

Full error: https://pastebin.com/gueVH0b3
