### ISSUE TITLE
Command Block and Multiverse plugin

### ISSUE THREAD

**Issue by Tryanium** [Multiverse/Multiverse-Core#2213]
Hi,

I've some troubles making the plugin works with some command block from a adventure map. Some of the command are "scoreboard" and some others... I think that's because the plugin overwrite the vanillia command ? Is there a way to avoid this? Is there any workaround? I've tried the map on a vanillia server and it's working! I also tried in a Spigot server without plugin and it's working properly.
I have no error in my console log.
Thx!

**Comment by benwoo1110** [comment]
The issue is that vanilla commands are not built for multi-world support. Thus, things like advancement and scoreboard may not work as expected as there is no per world support. Thus, it will load those info and data from the firstspawnworld (main world) of your server. 

A possible workaround is to look  for a scoreboard plugins that allow per world scoreboard and supports multiverse.

**Comment by Tryanium** [comment]
Thx, I'm going too check that!
