### ISSUE TITLE
Feature Request: Support for world-specific vanilla maps

### ISSUE THREAD

**Issue by CiaranGruber** [Multiverse/Multiverse-Core#2233]
Server type: PaperMC (1.15.2-R0.1-SNAPSHOT)
Multiverse-Core version: 4.1.0-b775
(Using Multiverse-Portals/Inventories, etc)

One thing I found is that Minecraft Vanilla maps tend to be glitchy as they are still stored in the main world and are not world-specific. It would be helpful if the vanilla maps were world-specific to reduce issues. This may also in turn allow for world-specific scoreboards, etc, and anything else that gets stored in the "data" folder in each world. Currently any maps in a players inventory will get corrupted upon entrance in that world which basically makes them unusable

**Comment by benwoo1110** [comment]
Due to how mc server worlds, playerdata and scoreboards and advancement can only be stored on your servers default world defined by level-name in your server.properties. For per world scoreboards, you probably want a plugin what such a feature. As for player inventory being corrupted, you will have to provide with more details on that and it will also probably be an issue better suited here https://github.com/Multiverse/Multiverse-Inventories/issues
