### ISSUE TITLE
I'm using version 2.5.0 of Multiverse-Core in 1.12.2 and Explosions aren't doing damage

### ISSUE THREAD

**Issue by adambash** [Multiverse/Multiverse-Core#2306]
I had removed every plugin and reinstalled to find out multiverse-core was causing a problem where Explosions didn't do damage. I have tried installing and using every other version of Multiverse and removing essentialsxprotect and worldguard but the problem wasn't fixed. Does anyone know how can I fix this issue.

**Comment by benwoo1110** [comment]
Closing this due to the lack of info and 2.5.0 + 1.12.2 is outdated. I can only suggest its an old bug by your server software or other plugins as mv doesn't have code to prevent explosion damage. If you still facing this issue you can open a new issue or join our discord at https://discord.gg/NZtfKky
