### ISSUE TITLE
set world gamemode

### ISSUE THREAD

**Issue by xBradx** [Multiverse/Multiverse-Core#2336]
I am using Java Edition 1.16.1, Paper 1.16.1, Multiverse-Core Version: 4.1.0-b775

I am trying to set my plotsquared world to the game mode creative.
I have edited game-mode in /plugins/Multiverse-Core/worlds.yml both manly 
and by command (/mvm set mode creative), but when I use /warp creative,
I am still in survival mode. Could someone please try to help me figure this out.

**Comment by nicegamer7** [comment]
The exact command should be `/mvm set gamemode creative {WORLD NAME}`. Try that and let us know if it works.

**Comment by xBradx** [comment]
no changes.
I was in the world when I originally did /mvm set mode creative, and I still had the same confirmation message..

**Comment by Modzzzzz** [comment]
@nicegamer7 i used that command on a world however it stayed the same after re warping back to it. im very confused.

**Comment by nicegamer7** [comment]
It's possible you have the `mv.bypass.gamemode.WORLDNAME` permission node (granted to OPped players), or another plugin is conflicting.

**Comment by benwoo1110** [comment]
Things to try:
* Only mv plugin installed
* Ensure you don't have `mv.bypass.gamemode.WORLDNAME` permissions (especially if you gave * perm node using a permission plugin)
* In mv config.yml is set as `teleportintercept: 'true'`
* Use latest build from https://ci.onarandombox.com/view/Multiverse/
* Try with `/mvtp` command instead of warp

**Comment by benwoo1110** [comment]
Closing it due to inactivity. Feel free to open a new issue if you need to or join our discord at https://discord.gg/NZtfKky
