### ISSUE TITLE
RandomTickSpeed Broken and Villegers not getting zombified

### ISSUE THREAD

**Issue by Gymblonski** [Multiverse/Multiverse-Core#2355]
The worlds were created with /mv create and this problems started appearing while I never had them with normally generating the default words. 
On /gamerule randomtickspeed its 3 but farms all still so slow
Its on hard difficulty but villagers get killed instead of zombified from zombies
Gateways in end are not working, not teleporting

Version 1.16.1

**Comment by nitewing76** [comment]
Do these problems exist in worlds not created by MultiVerse? Did you set these as your main world (in server.properties) to test if the same problems exist? What other steps did you take to ensure it's a MultiVerse bug & not a Spigot bug?

**Comment by benwoo1110** [comment]
To set gamerules of mv worlds, use `/mv gamerule <rule> <value> [worldname]` https://github.com/Multiverse/Multiverse-Core/wiki/Command-Reference#gamerule-command

Will be closing this issue due to in activity and lack of info (questions above ^^ need to be answered). If you are still having issues with MV, feel free to create a new issue following the issue template, or come to our discord at https://discord.gg/NZtfKky
