### ISSUE TITLE
[Bug]: error while create new world

### ISSUE THREAD

**Issue by Szybkimp3** [Multiverse/Multiverse-Core#2771]
### `/mv version -p` output

https://bit.ly/3kTftBK

### Server logs

https://mclo.gs/8vEmw0z

### Server Version

```shell
git-Purpur-1573 (MC: 1.18.2)*
```

### Bug Description

i cant create new world

### Steps to reproduce

?

### Agreements

- [ ] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [ ] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by susobcn** [comment]
I can´t create world in version 1.18.2 plugin`s
<a href="https://imgur.com/XlqopZj"><img src="https://i.imgur.com/XlqopZj.png" title="source: imgur.com" /></a>

**Comment by Firetop** [comment]
> What commands have you used to create the world and can i get the logs of the world being created
> 
> How to send the logs

I was able to recreate this with a normal: /mv create hardcore NORMAL command

**Comment by Firetop** [comment]
Here are my logs: https://mclo.gs/WXUpzcx

**Comment by zax71** [comment]
What server specs do you have? If you do not know just quote the host and package

**Comment by zax71** [comment]
Multiverse does not support piracy. [https://offlinemo.de/](https://offlinemo.de/)

**Comment by Firetop** [comment]
> Multiverse does not support piracy. https://offlinemo.de/

Just because it's offline mode does not mean we didn't buy the game LOL, it's called early 1.19 testing for a reason and the bug report is still valid LOL. You'll end up with the same report from someone else. AKA me.

Here are the same logs with the same error in Online mode: https://mclo.gs/JSozWMO

As to answer your original question; I am running this on my personal workstation with a RTX 3070 and a Ryzen 3800X and 32GB of memory, not a host.

This is being reopened on this Github issue here specifically for 1.19: https://github.com/Multiverse/Multiverse-Core/issues/2778
