### ISSUE TITLE
[Bug]: Error while create new world

### ISSUE THREAD

**Issue by Firetop** [Multiverse/Multiverse-Core#2778]
### `/mv version -p` output

https://bit.ly/3MXiEEl

### Server logs

https://mclo.gs/JSozWMO

### Server Version

```shell
This server is running Paper version git-Paper-28 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: b0eb4e0)
```

### Bug Description

Console errors when creating a new work in 1.19

### Steps to reproduce

1. Start 1.19 Paper server with Multiverse Plugin Loaded
2. Create a new world with the command: mv create hardcore normal
3. Review console output

### Agreements

- [x] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by willkroboth** [comment]
I've seen this as well, but I don't think it's a problem with Multiverse. If you look at where the errors start, there are a few lines that say:
```
[09:35:28 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-28 (MC: 1.19) ---
--
511 | [09:35:28 ERROR]: The server has not responded for 10 seconds! Creating thread dump
```
The output here isn't a bug or crash; Paper is creating a thread dump because the server has not responded for 10 seconds. This is probably caused by Multiverse (creating a world is a lot of work sometimes), but nothing has gone wrong. 

It looks like it took 29 seconds to create the world, which isn't too bad, but it was long enough that Paper was concerned something bad was happening. If you need to create worlds often, you can avoid these messages by changing the `early-warning-delay` value in the `/config/paper-global.yml` file to something like `45000` (the default is `10000`). This will make the server wait 45 seconds instead of 10 seconds until it gets concerned about the server not responding, giving plenty of time to create the world. 

Does that fix your issue, or is there another error I didn't see in the logs?

**Comment by SevenXD-DEV** [comment]
Can you link the download to this verison?

**Comment by Firetop** [comment]
> Can you link the download to this verison?

http://ci.onarandombox.com/job/Multiverse-Core/
