### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by psvks** [Multiverse/Multiverse-Core#2937]
### `/mv version -p` output

https://paste.gg/45d7548c89d1459390ed1cc8bb8ce018

### Server logs

https://paste.gg/p/anonymous/ac9d6731d9bb4e249d713ba2a9969b80/files/f7f4ec52db2946c58221ddb6bf3b7cde/raw

### Server Version

```shell
Paper 1.20.1
```

### Bug Description

A lot of ram Usage, first when you start the server you have 2gb of ram usage and when the time passes it increases to 6/8gbs of ram. And it really sucks because the server ping increases and the TPS decreases.

### Steps to reproduce

Just starting the server makes the bug happends

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Comment by Lildirt** [comment]
You're using an outdated version of Multiverse (4.3.1). The current release is 4.3.9. You checked the box & I really doubt you tried any deeper digging on this.
Additionally, we don't provide support for offline mode servers. Buy the game.

We won't be helping you diagnose your issue, but I can virtually guarantee you that Multiverse has nothing to do with it.
Use Spark to troubleshoot your server TPS issues. Find the correct support channel, because this isn't it.

**Comment by psvks** [comment]
Why are you so mad. I only wanted help...

**Comment by benwoo1110** [comment]
You have errors with other software that is unrelated to MV. Also having 7 worlds, it is normal to use 6/8gbs of ram. If you think its a huge issue, you can try use https://spark.lucko.me and see the performance stats.
```
Caused by: java.lang.NullPointerException: Cannot invoke "org.cloudburstmc.protocol.bedrock.data.ScoreInfo.getScoreboardId()" because "scoreInfo" is null
```

**Comment by psvks** [comment]
No, those worlds are not public for the members so, you can pretty much ignore them.
