### ISSUE TITLE
Request: Per-World Time

### ISSUE THREAD

**Issue by Inscrutable** [Multiverse/Multiverse-Core#79]
Is it possible to implement per-world time with a multiworld setup?

Current world time modifications affect all worlds in MV2 (RB1060)
It would be quite nice to allow different time zones in each world.
(I hope it's not a stupid question. I haven't seen this requested elsewhere)

**Comment by Xinoms** [comment]
lol, now in 2016 I'm having the exact same problem.
Whenever I set the time in the main world of my server it changes the time in the other world I have on the server, is there nay news on whether theres a solution to this???

**Comment by MarkehMe** [comment]
Would Multiverse be open to a PR?

**Comment by FernFerret** [comment]
Yep! I noticed we had a PR come in last week to fix some tests, but I
haven't had any time to look at it.

**Comment by Supuhstar** [comment]
This is still an issue...

**Comment by Jadiction** [comment]
@Supuhstar Replying for the sake of other's stumbling upon this possibly needing help. That is doable with the gamerule "doDaylightCycle". I currently do as such with my worlds while using Multiverse and it works fine. I also use /time set without it messing up other worlds as well, but that is with Essentials, not the vanilla version.

**Comment by dumptruckman** [comment]
I implied in #1824 that this behavior is not *caused* by multiverse. If you had another plugin that added worlds, you'd encounter the same problem. The vanilla time command works fine in vanilla because there's only 1 world where time is noticeable. When you add in the concept of multiple worlds, the command works just the same as before, setting the overall server time rather than the individual world time.

Ideally, this "problem" should be fixed at a server implementation level (craftbukkit/spigot) since that is the reason why multiple worlds are possible. If they refuse to fix it, we could consider a feature request for an `/mv time` command or some such to allow setting per world time. However, I'm sure other plugins exist that let you do this.

**Comment by Jadiction** [comment]
I use this plugin: https://dev.bukkit.org/projects/customtime
for per-world time modifications. For example, you can make day time 10 minutes and nighttime 2 minutes, or day/night disabled as well.

**Comment by benfoster04** [comment]
I don't like bumping old threads. However, I do believe this is something that should be taken seriously and implemented directly into Multiverse Core, not into some sub plugin. As kindly aforementioned by @dumptruckman, a command along the lines of `/mv time` or maybe a complete override on the `/time` command should be implemented.

**Comment by Jadiction** [comment]
@benfoster04 I'm sure if someone opened a PR for it, DTM would look at it and merge it assuming it lives up to the standards & works.

**Comment by BornToDoStuff** [comment]
I would really appreciate being able to control time with /mv time or a /time override. I have many worlds and being able to give a time command to them separately would be very convenient.

**Comment by benwoo1110** [comment]
This issue is outdated and closed, if you wish to have a new feature request, please open a new issue following the issue template. Thanks!

**Comment by KneesDev** [comment]
It's been over a decade and this issue is not fixed.
